baseURL = "https://stevenazy.github.io/"    # 博客网址
languageCode = "zh-CN"              # 网站语言。国际化需要
title = "StevenBlog"                  # 博客的名字。浏览器 title 上也会显示
hasCJKLanguage = true               # 统计汉字
theme = "hugo-kiera"                  # 主题

[pagination]
  pagerSize = 11                      # 每页的文章数
enableEmoji = true                  # 支持 Emoji
enableRobotsTXT = true              # 支持 robots.txt
googleAnalytics = ""                # Google 统计 id

pygmentsUseClasses = true # 使用自定义的代码高亮样式

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
  tagline = "Talk is cheap, show me code."

  [params.author]
  name = "steven"
  email = 'stevenazy@outlook.com'
  github = "StevenAZy"
  twitter = "CLLOVEZ"